#!/usr/bin/python3

import sys
import re

commit_msg_filepath = sys.argv[1]

regex = '^(build|ci|docs|feat|fix|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: [A-Z1]+-[0-9]+ ([\\w ])([\\w ])+([\\s\\S]*)'

with open(commit_msg_filepath, 'r+') as f:
    commit_msg = f.read()
    if not re.match(regex, commit_msg):
        print('Commit message did not matched regex, please check commit message style')
        sys.exit(1)
