name: Run python tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies with poetry
        run: poetry install

      # Установка PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      # Запуск тестов для homework_1
      - name: Run Test Task 1
        run: poetry run pytest -vv --strict --showlocals ./tests/test_homework_1.py

      # Запуск тестов для homework_2
      - name: Run Test Task 2
        run: poetry run pytest -vv --strict --showlocals ./tests/test_homework_2.py

      # Запуск тестов для homework_4
      - name: Run Test Task 4
        run: poetry run pytest -vv --strict --showlocals ./tests/test_homework_4.py
